language: cpp
cache: ccache

env:
  global:
    - CCACHE_COMPRESS=1
    - CCACHE_CPP2=yes



matrix:
  include:
    - os: linux
      env: DIST=ubuntu1604 COMPILER=gcc
      services: [docker]
      sudo: true
    - os: linux
      env: DIST=ubuntu1604 COMPILER=clang
      services: [docker]
      sudo: true
    - os: linux
      env: DIST=ubuntu1804 COMPILER=gcc
      services: [docker]
      sudo: true
    - os: linux
      env: DIST=ubuntu1804 COMPILER=clang
      services: [docker]
      sudo: true
    - os: osx
      compiler: clang
      env: PYTHONVERSION=2.7
    - os: osx
      compiler: clang
      env: PYTHONVERSION=3.4
  allow_failures:
    - os: osx
      env: PYTHONVERSION=3.4

sudo: false

install:
  - ./.travis/install.sh

before_script:
  - ./.travis/before_script.sh

script:
  - ./.travis/script.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a21dbde2d416245fd698
    on_success: always
    on_failure: always
    on_start: false
